### ISSUE TITLE
Results / Final leaderboard - As a player, I want to view the final leaderboard at the end of each game, so I can see where I ranked among the participants in that game session.

### ISSUE THREAD

**Issue by domeniku7** [sopra-fs24-group-40/mapquestor-server#10]
- After a game session ends, all players are automatically directed to the
results page displaying the final leaderboard.
- The final leaderboard shows the ranking of players based on their
performance in the game session.
- Each player's rank, username, and score are visible on the leaderboard.
- Players can see their own highlight in the leaderboard for easy
identification.
- There is an option to navigate from the results page to the main menu or to play again. 
- [x] sopra-fs24-group-40/mapquestor-server#57
- [x] sopra-fs24-group-40/mapquestor-client#15
- [x] sopra-fs24-group-40/mapquestor-client#16
