### ISSUE TITLE
Restart game - As the game creator, I want the ability to restart the game after it has ended, so that players can play again without needing to exit to the main menu.

### ISSUE THREAD

**Issue by domeniku7** [sopra-fs24-group-40/mapquestor-server#11]
- At the end of a game, the game creator is presented with an option to
restart the game.
- Over the play again button, it is displayed how many players want to play again. 
- Every original player has the option to notify the creator to play again. 
- Only the creator can restart the game.  
- If the creator decides to not play again, every player is set back to the main dashboard. 
- The game settings from the previous session are preserved for the new session but can be adjusted by the creator before starting. 
- Players who choose to join the new session are automatically added to the game lobby, and the game starts once the creator initiates it. 
- Players who do not respond within a set time limit (60s) are returned to the main menu. 
- [ ] sopra-fs24-group-40/mapquestor-client#10
- [ ] sopra-fs24-group-40/mapquestor-client#11
- [ ] sopra-fs24-group-40/mapquestor-client#13
- [ ] sopra-fs24-group-40/mapquestor-server#51
- [ ] sopra-fs24-group-40/mapquestor-server#52

**Comment by bhalf** [comment]
https://github.com/sopra-fs24-group-40/mapquestor-server/commit/1a57c0cc4adf1c603102b9611102b5f8e8d63afe
