### ISSUE TITLE
User Overview - As a logged-in user, I want to inspect a registered user’s profile by selecting the username from a list.

### ISSUE THREAD

**Issue by domeniku7** [sopra-fs24-group-40/mapquestor-server#2]
- A user can view a list of all registered users (users overview) and select each one for inspection.
- By clicking on a username in the user’s overview, you are redirected to a
profile page of the selected user.
- The profile page contains the following data belonging to the selected user: username, online status, total points (option to see different stats via various criteria) and an (optional) avatar. 
- The dashboard and the profile page are only accessible for logged in
users.
- (Optional) An avatar image is optional and can only be set on the profile
page.
- [x] sopra-fs24-group-40/mapquestor-client#26
- [x] sopra-fs24-group-40/mapquestor-client#27
- [x] sopra-fs24-group-40/mapquestor-client#28
- [x] sopra-fs24-group-40/mapquestor-client#5
- [x] sopra-fs24-group-40/mapquestor-server#27
- [x] sopra-fs24-group-40/mapquestor-client#31
