### ISSUE TITLE
Joining a Lobby - As a user, I want to join lobbies from other users via their lobby ID.

### ISSUE THREAD

**Issue by domeniku7** [sopra-fs24-group-40/mapquestor-server#5]
- When a user clicks on the “Join Lobby” button, the user is prompted with
an input field.
- After entering a valid lobby ID and pressing the “Join” button , the user
will automatically join the game room of the creator.
- The joined user can see all other users which are partaking in this lobby.
- The joined user can see the settings of the game.
- [x] sopra-fs24-group-40/mapquestor-server#33
- [x] sopra-fs24-group-40/mapquestor-client#9
- [x] sopra-fs24-group-40/mapquestor-server#35
