### ISSUE TITLE
Game Experience with Interaction - As a user i want to have a range of features, to offer fun and usefulness.

### ISSUE THREAD

**Issue by domeniku7** [sopra-fs24-group-40/mapquestor-server#8]
- The leaderboard, located on the left side of the screen, should display user
rankings in real time.
- A movable map feature should be accessible within the game, offering a
view of various countries and cities.
- Players should be able to navigate the map effortlessly, enhancing
geographical knowledge.
- A type in field should be available for users to input their answers during
the gameplay.
- A hint field over the map should accompany the type-in field on the right side, providing users with additional clues or guidance. 
- A timer is visible in the header of how long the round will still last.	 
- [x] sopra-fs24-group-40/mapquestor-client#22
- [x] sopra-fs24-group-40/mapquestor-client#23
- [x] sopra-fs24-group-40/mapquestor-client#29
- [x] sopra-fs24-group-40/mapquestor-server#43
