### ISSUE TITLE
Game Logic - As a creator, I need a robust game logic for assessing player answers and ensuring fair scoring. 

### ISSUE THREAD

**Issue by domeniku7** [sopra-fs24-group-40/mapquestor-server#9]
- The system should assign points to users based correctness of their
answers, with a quicker response getting higher scores.
- Every round has a time limit. After the timer expires , the next round will
st art.
- Every player has one De lay Joker ””, if this one is used , the image for all
other players will be shown with a ten second delay , in the nex t round.
- Every player has o ne Hint Remover Joker ””, if this one is used, the hint of
how m any let ters ther e are in the sought after word ( city or country will
not be visi ble the next round.
- If multiple players use the same joker simultaneously, they (all the p layers
who used the joker) will not be affected by its effect.
- Jokers can n ot be car ried over to an other session. They wil l diminish after
each session.
- The game should conclude after several rounds (“X” rounds), providing a
clear endpoint.
- [x] sopra-fs24-group-40/mapquestor-client#30
- [x] sopra-fs24-group-40/mapquestor-client#18
- [x] sopra-fs24-group-40/mapquestor-server#46
- [x] sopra-fs24-group-40/mapquestor-client#7
